export enum PokemonNature {
  BOLD = 'Assuré',
  QUIRKY = 'Bizarre',
  BRAVE = 'Brave',
  CALM = 'Calme',
  QUIET = 'Discret',
  DOCILE = 'Docile',
  MILD = 'Doux',
  RASH = 'Foufou',
  GENTLE = 'Gentil',
  HARDY = 'Hardi',
  JOLLY = 'Jovial',
  LAX = 'Lâche',
  IMPISH = 'Malin',
  SASSY = 'Malpoli',
  NAUGHTY = 'Mauvais',
  MODEST = 'Modeste',
  NAIVE = 'Naïf',
  HASTY = 'Pressé',
  CAREFUL = 'Prudent',
  BASHFUL = 'Pudique',
  RELAXED = 'Relax',
  ADAMANT = 'Rigide',
  SERIOUS = 'Sérieux',
  LONELY = 'Solo',
  TIMID = 'Timid',
}

export const natureDescMapping: Record<PokemonNature, string> = {
  [PokemonNature.BOLD]: '+Def, -Atq',
  [PokemonNature.QUIRKY]: 'Neutre',
  [PokemonNature.BRAVE]: '+Atq, -Vit',
  [PokemonNature.CALM]: '+Def Spé, -Atq ',
  [PokemonNature.QUIET]: '+Atq Spé, -Vit',
  [PokemonNature.DOCILE]: 'Neutre',
  [PokemonNature.MILD]: '+Atq Spé, -Def',
  [PokemonNature.RASH]: '+Atq Spé, -Def Spé',
  [PokemonNature.GENTLE]: '+Def Spé, -Def',
  [PokemonNature.HARDY]: 'Neutre',
  [PokemonNature.JOLLY]: '+Vit, -Atq Spé',
  [PokemonNature.LAX]: '+Def, -Def Spé',
  [PokemonNature.IMPISH]: '+Def, -Atq Spé',
  [PokemonNature.SASSY]: '+Def, Spé -Vit',
  [PokemonNature.NAUGHTY]: '+Atq, -Def Spé',
  [PokemonNature.MODEST]: '+Atq Spé, -Atq',
  [PokemonNature.NAIVE]: '+Vit, -Def Spé',
  [PokemonNature.HASTY]: '+Vit, -Def',
  [PokemonNature.CAREFUL]: '+Def Spé, -Atq Spé',
  [PokemonNature.BASHFUL]: 'Neutre',
  [PokemonNature.RELAXED]: '+Def, -Vit',
  [PokemonNature.ADAMANT]: '+Atq, -Atq Spé',
  [PokemonNature.SERIOUS]: 'Neutre',
  [PokemonNature.LONELY]: '+Atq, -Def',
  [PokemonNature.TIMID]: '+Atq Spé, -Atq',
};
