export enum PokemonNature {
  BOLD = 'Assuré',
  QUIRKY = 'Bizarre',
  BRAVE = 'Brave',
  CALM = 'Calme',
  QUIET = 'Discret',
  DOCILE = 'Docile',
  MILD = 'Doux',
  RASH = 'Foufou',
  GENTLE = 'Gentil',
  HARDY = 'Hardi',
  JOLLY = 'Jovial',
  LAX = 'Lâche',
  IMPISH = 'Malin',
  SASSY = 'Malpoli',
  NAUGHTY = 'Mauvais',
  MODEST = 'Modeste',
  NAIVE = 'Naïf',
  HASTY = 'Pressé',
  CAREFUL = 'Prudent',
  BASHFUL = 'Pudique',
  RELAXED = 'Relax',
  ADAMANT = 'Rigide',
  SERIOUS = 'Sérieux',
  LONELY = 'Solo',
  TIMID = 'Timid',
}
