export enum PokemonType {
  FIGHTING = 'Combat',
  FLYING = 'Vol',
  POISON = 'Poison',
  GROUND = 'Sol',
  ROCK = 'Roche',
  BUG = 'Insecte',
  GHOST = 'Spectre',
  STEEL = 'Acier',
  FIRE = 'Feu',
  WATER = 'Eau',
  GRASS = 'Plante',
  ELECTRIC = 'Électrik',
  PSY = 'Psy',
  ICE = 'Glace',
  DRAGON = 'Dragon',
  FAIRY = 'Fée',
  DARK = 'Ténèbres',
  NORMAL = 'Normal',
}
